name: gumblino
favicon: null
layout_spectrum: 0.49904
typography_spectrum: 0.26879
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ede7db'
    - '#260402'
    - '#a22810'
    - '#e0b0b0'
    - '#a55451'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
